In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("../Data/movies_metadata.csv", low_memory=False)

In [27]:
df.sample(10)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
8190,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,16358,tt0349416,en,Eulogy,A black comedy that follows three generations ...,...,2004-10-15,0.0,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Eulogy,False,6.4,34.0
19498,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,168217,tt0016022,en,Lightnin',Set in a hotel straddling the border between C...,...,1925-08-23,0.0,104.0,[],Released,NaN,Lightnin',False,5.0,1.0
32857,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}]",NaN,242262,tt3484266,it,La sedia della felicità,"Dino craft practice tattoos, Bruna is a beauti...",...,2013-11-24,0.0,89.0,"[{'iso_639_1': 'it', 'name': 'Italiano'}]",Released,NaN,La sedia della felicità,False,5.6,21.0
3846,False,"{'id': 12203, 'name': 'Drunken Master Collecti...",0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,12207,tt0111512,cn,醉拳二,Returning home with his father after a shoppin...,...,1994-02-03,0.0,102.0,"[{'iso_639_1': 'cn', 'name': '广州话 / 廣州話'}]",Released,He's got a secret weapon with a lot of kick.,The Legend of Drunken Master,False,7.2,246.0
5736,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,32625,tt0295238,en,Personal Velocity,Three women's escapes from their afflicted liv...,...,2002-01-01,0.0,86.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Personal Velocity,False,5.0,11.0
5970,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,41291,tt0084445,en,One from the Heart,Hank and Frannie don't seem to be able to live...,...,1982-02-12,0.0,107.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Francis Coppola classic that audiences nev...,One from the Heart,False,5.6,20.0
32073,False,NaN,0,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...",NaN,342896,tt2949196,en,I-Lived,Josh Fosse is a 20something guy whose life is ...,...,2015-07-03,0.0,97.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,I-Lived,False,4.9,9.0
12409,False,NaN,0,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",NaN,113788,tt0018972,en,Hangman's House,"Forced by her mean-spirited father, Lord Chief...",...,1928-05-13,0.0,80.0,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,NaN,Hangman's House,False,6.3,4.0
6435,False,"{'id': 289531, 'name': 'Gator Collection', 'po...",0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",NaN,4984,tt0070915,en,White Lightning,An ex con teams up with federal agents to help...,...,1973-08-06,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"If You Haven't Seen ""White Lightning"" You Have...",White Lightning,False,6.2,21.0
34676,False,"{'id': 105764, 'name': 'The Tall Blond Man Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,10939,tt0072080,fr,Le retour du grand blond,With 'little captain' Cambrai raising serious ...,...,1974-11-12,0.0,81.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,NaN,The Return of the Tall Blond Man with One Blac...,False,6.8,31.0

In [6]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [8]:
df.shape

(45466, 24)

In [9]:
df.dtypes

adult                     object
belongs_to_collection     object
budget                    object
genres                    object
homepage                  object
id                        object
imdb_id                   object
original_language         object
original_title            object
overview                  object
popularity                object
poster_path               object
production_companies      object
production_countries      object
release_date              object
revenue                  float64
runtime                  float64
spoken_languages          object
status                    object
tagline                   object
title                     object
video                     object
vote_average             float64
vote_count               float64
dtype: object

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [15]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(17)

In [20]:
df[df.duplicated()]

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
1465,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,105045,tt0111613,de,Das Versprechen,"East-Berlin, 1961, shortly after the erection ...",...,1995-02-16,0.0,115.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,"A love, a hope, a wall.",The Promise,False,5.0,1.0
9165,False,NaN,0,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,5511,tt0062229,fr,Le Samouraï,Hitman Jef Costello is a perfectionist who alw...,...,1967-10-25,39481.0,105.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,There is no solitude greater than that of the ...,Le Samouraï,False,7.9,187.0
9327,False,NaN,0,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",NaN,23305,tt0295682,en,The Warrior,"In feudal India, a warrior (Khan) who renounce...",...,2001-09-23,0.0,86.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,The Warrior,False,6.3,15.0
13375,False,NaN,0,"[{'id': 53, 'name': 'Thriller'}, {'id': 9648, ...",NaN,141971,tt1180333,fi,Blackout,Recovering from a nail gun shot to the head an...,...,2008-12-26,0.0,108.0,"[{'iso_639_1': 'fi', 'name': 'suomi'}]",Released,Which one is the first to return - memory or t...,Blackout,False,6.7,3.0
16764,False,NaN,0,"[{'id': 53, 'name': 'Thriller'}, {'id': 9648, ...",NaN,141971,tt1180333,fi,Blackout,Recovering from a nail gun shot to the head an...,...,2008-12-26,0.0,108.0,"[{'iso_639_1': 'fi', 'name': 'suomi'}]",Released,Which one is the first to return - memory or t...,Blackout,False,6.7,3.0
21165,False,NaN,0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",NaN,119916,tt0080000,en,The Tempest,"Prospero, the true Duke of Milan is now living...",...,1980-02-27,0.0,123.0,[],Released,NaN,The Tempest,False,0.0,0.0
21854,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",NaN,152795,tt1821641,en,The Congress,More than two decades after catapulting to sta...,...,2013-05-16,455815.0,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,The Congress,False,6.4,165.0
22151,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 27, 'nam...",http://www.daysofdarknessthemovie.com/,18440,tt0499456,en,Days of Darkness,When a comet strikes Earth and kicks up a clou...,...,2007-01-01,0.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Days of Darkness,False,5.0,5.0
23044,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,25541,tt1327820,da,Broderskab,Former Danish servicemen Lars and Jimmy are th...,...,2009-10-21,0.0,90.0,"[{'iso_639_1': 'da', 'name': 'Dansk'}]",Released,NaN,Brotherhood,False,7.1,21.0
24844,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.dealthemovie.com/,11115,tt0446676,en,Deal,As an ex-gambler teaches a hot-shot college ki...,...,2008-01-29,0.0,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Deal,False,5.2,22.0
28860,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,168538,tt0084387,en,Nana,"In Zola's Paris, an ingenue arrives at a tony ...",...,1983-06-13,0.0,92.0,[],Released,NaN,"Nana, the True Key of Pleasure",False,4.7,3.0
29374,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...",NaN,42495,tt0067306,en,King Lear,"King Lear, old and tired, divides his kingdom ...",...,1971-02-04,0.0,137.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Rumored,NaN,King Lear,False,8.0,3.0
35798,False,"{'id': 158365, 'name': 'Why We Fight', 'poster...",0,"[{'id': 99, 'name': 'Documentary'}]",NaN,159849,tt0173769,en,Why We Fight: Divide and Conquer,"The third film of Frank Capra's 'Why We Fight""...",...,1943-01-01,0.0,57.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Why We Fight: Divide and Conquer,False,5.0,1.0
38871,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,99080,tt0022537,en,The Viking,"Originally called White Thunder, American prod...",...,1931-06-21,0.0,70.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Actually produced during the Great Newfoundlan...,The Viking,False,0.0,0.0
40040,False,NaN,980000,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",NaN,298721,tt2818654,th,รักที่ขอนแก่น,"In a hospital, ten soldiers are being treated ...",...,2015-09-02,0.0,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Cemetery of Splendour,False,4.4,50.0
40276,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}]",NaN,97995,tt0127834,en,Seven Years Bad Luck,"After breaking a mirror in his home, superstit...",...,1921-02-06,0.0,62.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Seven Years Bad Luck,False,5.6,4.0
45265,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,265189,tt2121382,sv,Turist,"While holidaying in the French Alps, a Swedish...",...,2014-08-15,1359497.0,118.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,NaN,Force Majeure,False,6.8,255.0

In [25]:
df = df.drop_duplicates().reset_index(drop=True)

In [28]:
df.shape #17 rows duplicate

(45449, 24)

In [29]:
df = df[['title', 'overview', 'genres','tagline','vote_average','popularity']]

In [30]:
df

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519
...,...,...,...,...,...,...
45444,Subdue,Rising and falling between a man and woman.,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",Rising and falling between a man and woman,4.0,0.072051
45445,Century of Birthing,An artist struggles to finish his work while a...,"[{'id': 18, 'name': 'Drama'}]",NaN,9.0,0.178241
45446,Betrayal,"When one of her hits goes wrong, a professiona...","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",A deadly game of wits.,3.8,0.903007
45447,Satan Triumphant,"In a small town live two brothers, one a minis...",[],NaN,0.0,0.003503
45448,Queerama,50 years after decriminalisation of homosexual...,[],NaN,0.0,0.163015

In [31]:
df=df.dropna(subset=['title'])

In [33]:
df['overview'] = df['overview'].fillna('')

C:\Users\DELL\AppData\Local\Temp\ipykernel_18856\214675183.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['overview'] = df['overview'].fillna('')

In [34]:
df['overview'].isnull().sum()

np.int64(0)

In [35]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [36]:
df.iloc[0]

title                                                   Toy Story
overview        Led by Woody, Andy's toys live happily in his ...
genres          [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
tagline                                                       NaN
vote_average                                                  7.7
popularity                                              21.946943
Name: 0, dtype: object

In [38]:
import ast
df.loc[:, 'genres'] = df['genres'].apply(
    lambda x: " ".join([i['name'] for i in ast.literal_eval(x)])
)

SyntaxError: invalid syntax (<unknown>, line 1)

In [39]:
df['genres'].head()

0     Animation Comedy Family
1    Adventure Fantasy Family
2              Romance Comedy
3        Comedy Drama Romance
4                      Comedy
Name: genres, dtype: object

In [40]:
df['tagline'] = df['tagline'].fillna('')

C:\Users\DELL\AppData\Local\Temp\ipykernel_18856\733522008.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tagline'] = df['tagline'].fillna('')

In [41]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [42]:
df['tags'] = df['overview']+ " " + df['genres'] +" "+ df['tagline']

C:\Users\DELL\AppData\Local\Temp\ipykernel_18856\2295794173.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['overview']+ " " + df['genres'] +" "+ df['tagline']

In [43]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [44]:
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [46]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re  #regular expression

In [47]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...

True

In [56]:
stop_words=set(stopwords.words('english'))
lemmatizer= WordNetLemmatizer()

In [57]:
def preprocess_text(text):
  #lowercase
  text = str(text).lower()
  #removed  punctuations
  text = re.sub(r'[^a-zA-Z\s]', '', text)

  words = text.split()
  #remove stopwords
  words = [word for word in words if word not in stop_words]

  #lemmatize
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [58]:
df['tags'] = df['tags'].apply(preprocess_text)

C:\Users\DELL\AppData\Local\Temp\ipykernel_18856\684871197.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(preprocess_text)

In [59]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [64]:
df=df.reset_index(drop=True)

In [65]:
indices = pd.Series(df.index,index = df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45438
Century of Birthing            45439
Betrayal                       45440
Satan Triumphant               45441
Queerama                       45442
Length: 45443, dtype: int64

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [67]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [68]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [69]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1548209 stored elements and shape (45443, 50000)>

In [70]:
from sklearn.metrics.pairwise import cosine_similarity

In [71]:
def recommend(title, n = 10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [72]:
recommend('Avatar',5)

26547                  Avatar 2
13883      The Inhabited Island
26553            Thor: Ragnarok
43428    Moontrap: Target Earth
9949         A Trip to the Moon
Name: title, dtype: object

In [74]:
recommend('Avenger',5)

41883     Dexter's Laboratory: Ego Trip
4367                             D.O.A.
871              The Philadelphia Story
7842     Now You See Him, Now You Don't
5054                          Hopscotch
Name: title, dtype: object

In [76]:
import pickle

pickle.dump(tfidf_matrix, open('../models/tfidf_matrix.pkl', 'wb'))
pickle.dump(indices, open('../models/indices.pkl', 'wb'))
pickle.dump(tfidf, open('../models/tfidf.pkl', 'wb'))

df.to_pickle('../models/df.pkl')